# Generated by Django 5.1 on 2025-04-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronet_pilot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=255, null=True),
        ),
    ]
