events {}

http {
    server {
        listen 80;

        location /api/ {
            proxy_pass http://74.207.237.6:5173/;
        }

        location /django/ {
            proxy_pass http://74.207.237.6:8000/;
        }
    }
}
