# Generated by Django 5.1 on 2025-04-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_category_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remaining_stock',
            field=models.IntegerField(default=0),
        ),
    ]
