# Generated by Django 5.1 on 2025-03-21 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agronet_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
